name: Deploy Tesla Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      influxdb:
        image: influxdb:2.7
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: admin
          DOCKER_INFLUXDB_INIT_PASSWORD: tesla123456
          DOCKER_INFLUXDB_INIT_ORG: tesla_org
          DOCKER_INFLUXDB_INIT_BUCKET: tesla_data
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tesla_token_123456
        ports:
          - 8086:8086
        options: >-
          --health-cmd "curl -f http://localhost:8086/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import tesla_vis; print('App imports successfully')"
        python -c "import tesla_influxdb; print('InfluxDB module imports successfully')"
      env:
        INFLUXDB_URL: http://localhost:8086
        INFLUXDB_TOKEN: tesla_token_123456
        INFLUXDB_ORG: tesla_org
        INFLUXDB_BUCKET: tesla_data

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Railway
      uses: railway/deploy@v1.0.0
      with:
        service: tesla-dashboard
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 